//
//  String.swift
//  F.I.R.E.
//
//  Created by Денис Сторожев on 20.05.2023.
//

import Foundation


final class strings :ObservableObject {
    let word = [
            NSLocalizedString("word_0", comment: ""),
            NSLocalizedString("word_1", comment: ""),
            NSLocalizedString("word_2", comment: ""),
            NSLocalizedString("word_3", comment: ""),
            NSLocalizedString("word_4", comment: ""),
            NSLocalizedString("word_5", comment: ""),
            NSLocalizedString("word_6", comment: ""),
            NSLocalizedString("word_7", comment: ""),
            NSLocalizedString("word_8", comment: ""),
            NSLocalizedString("word_9", comment: ""),
            NSLocalizedString("word_10", comment: ""),
            NSLocalizedString("word_11", comment: ""),
            NSLocalizedString("word_12", comment: ""),
            NSLocalizedString("word_13", comment: ""),
            NSLocalizedString("word_14", comment: ""),
            NSLocalizedString("word_15", comment: ""),
            NSLocalizedString("word_16", comment: ""),
            NSLocalizedString("word_17", comment: ""),
            NSLocalizedString("word_18", comment: ""),
            NSLocalizedString("word_19", comment: ""),
            NSLocalizedString("word_20", comment: ""),
            NSLocalizedString("word_21", comment: ""),
            NSLocalizedString("word_22", comment: ""),
            NSLocalizedString("word_23", comment: ""),
            NSLocalizedString("word_24", comment: ""),
            NSLocalizedString("word_25", comment: ""),
            NSLocalizedString("word_26", comment: ""),
            NSLocalizedString("word_27", comment: ""),
            NSLocalizedString("word_28", comment: ""),
            NSLocalizedString("word_29", comment: ""),
            NSLocalizedString("word_30", comment: ""),
            NSLocalizedString("word_31", comment: ""),
            NSLocalizedString("word_32", comment: ""),
            NSLocalizedString("word_33", comment: ""),
            NSLocalizedString("word_34", comment: ""),
            NSLocalizedString("word_35", comment: ""),
            NSLocalizedString("word_36", comment: ""),
            NSLocalizedString("word_37", comment: ""),
            NSLocalizedString("word_38", comment: ""),
            NSLocalizedString("word_39", comment: ""),
            NSLocalizedString("word_40", comment: ""),
            NSLocalizedString("word_41", comment: ""),
            NSLocalizedString("word_42", comment: ""),
            NSLocalizedString("word_43", comment: ""),
            NSLocalizedString("word_44", comment: ""),
            NSLocalizedString("word_45", comment: ""),
            NSLocalizedString("word_46", comment: ""),
            NSLocalizedString("word_47", comment: ""),
            NSLocalizedString("word_48", comment: ""),
            NSLocalizedString("word_49", comment: ""),
            NSLocalizedString("word_50", comment: ""),
            NSLocalizedString("word_51", comment: ""),
            NSLocalizedString("word_52", comment: ""),
            NSLocalizedString("word_53", comment: ""),
            NSLocalizedString("word_54", comment: ""),
            NSLocalizedString("word_55", comment: ""),
            NSLocalizedString("word_56", comment: ""),
            NSLocalizedString("word_57", comment: ""),
            NSLocalizedString("word_58", comment: ""),
            NSLocalizedString("word_59", comment: ""),
            NSLocalizedString("word_60", comment: ""),
            NSLocalizedString("word_61", comment: ""),
            NSLocalizedString("word_62", comment: ""),
            NSLocalizedString("word_63", comment: ""),
            NSLocalizedString("word_64", comment: ""),
            NSLocalizedString("word_65", comment: ""),
            NSLocalizedString("word_66", comment: ""),
            NSLocalizedString("word_67", comment: ""),
            NSLocalizedString("word_68", comment: ""),
            NSLocalizedString("word_69", comment: ""),
            NSLocalizedString("word_70", comment: ""),
            NSLocalizedString("word_71", comment: ""),
            NSLocalizedString("word_72", comment: ""),
            NSLocalizedString("word_73", comment: ""),
            NSLocalizedString("word_74", comment: ""),
            NSLocalizedString("word_75", comment: ""),
            NSLocalizedString("word_76", comment: ""),
            NSLocalizedString("word_77", comment: ""),
            NSLocalizedString("word_78", comment: ""),
            NSLocalizedString("word_79", comment: ""),
            NSLocalizedString("word_80", comment: ""),
            NSLocalizedString("word_81", comment: ""),
            NSLocalizedString("word_82", comment: ""),
            NSLocalizedString("word_83", comment: ""),
            NSLocalizedString("word_84", comment: ""),
            NSLocalizedString("word_85", comment: ""),
            NSLocalizedString("word_86", comment: ""),
            NSLocalizedString("word_87", comment: ""),
            NSLocalizedString("word_88", comment: ""),
            NSLocalizedString("word_89", comment: ""),
            NSLocalizedString("word_90", comment: ""),
            NSLocalizedString("word_91", comment: ""),
            NSLocalizedString("word_92", comment: ""),
            NSLocalizedString("word_93", comment: ""),
            NSLocalizedString("word_94", comment: ""),
            NSLocalizedString("word_95", comment: ""),
            NSLocalizedString("word_96", comment: ""),
            NSLocalizedString("word_97", comment: ""),
            NSLocalizedString("word_98", comment: ""),
            NSLocalizedString("word_99", comment: ""),
            
        // короче так для каждого
    ]
}
